### ISSUE TITLE
Plugin crashes when trying to do any command (fl 1.16.2, latests)

### ISSUE THREAD

**Issue by jonesy-b-dev** [asmpro7/StatisFlow#2]
When I type just st already it crashes flow launcher with the following log:
```
Flow Launcher version: 1.16.2
OS Version: 18363.752
IntPtr Length: 8

x64: True

Python Path: C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\pythonw.exe
Node Path: C:\Program Files\nodejs\node.exe
Date: 01/09/2024 09:47:26
Exception:
Statis Exception: 
Websites: https://github.com/asmpro7/StatisFlow
Author: Ahmed ElSaeed
Version: 1.1.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: An error occurred trying to start process 'C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\pythonw.exe' with working directory 'C:\Users\xvanhunen\AppData\Roaming\FlowLauncher\Plugins\Statis-1.1.0'. Access is denied.
 ---> System.ComponentModel.Win32Exception (5): An error occurred trying to start process 'C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\pythonw.exe' with working directory 'C:\Users\xvanhunen\AppData\Roaming\FlowLauncher\Plugins\Statis-1.1.0'. Access is denied.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 244
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 311
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 194
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass139_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 849
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults(Boolean isReQuery) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 850
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

Log file: 
[2024-01-09.txt](https://github.com/asmpro7/StatisFlow/files/13871283/2024-01-09.txt)

**Comment by asmpro7** [comment]
I don't see any error in the plugin from log. 
try to reinstall it, if the problem still appears ask in flow launcher community.

**Comment by jonesy-b-dev** [comment]
Reinstalling sadly did not fix the issue. Ill check up on the flow launcher community

**Comment by NoPlagiarism** [comment]
Related to https://github.com/Flow-Launcher/Flow.Launcher/issues/1951
